# Generated by Django 2.2.28 on 2024-02-17 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postfile',
            name='media_type',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='postfile',
            name='thumbnail',
            field=models.FileField(blank=True, null=True, upload_to='post_files'),
        ),
    ]
