# Generated by Django 2.2.28 on 2024-02-17 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_postal_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='user',
            name='longitude',
        ),
    ]
