# Generated by Django 2.2.28 on 2024-02-18 07:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20240217_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='blocked_users',
            field=models.ManyToManyField(blank=True, related_name='blockers', to=settings.AUTH_USER_MODEL),
        ),
    ]
