# Generated by Django 2.2.28 on 2024-04-16 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_blocked_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='denied_contributor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_paused',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='missing_information',
            field=models.TextField(blank=True),
        ),
    ]
