version: "3"

services:
  web:
    depends_on:
      - postgres
      - redis
  postgres:
    image: postgres:12
  redis:
    image: redis:5
    ports:
      - "6379:6379"
  celery:
    build: .
    command: celery -A blessn worker --loglevel=INFO
    depends_on:
      - web
      - redis
      - postgres
    env_file:
      - .env
    volumes:
      - ./:/opt/webapp