# Generated by Django 2.2.28 on 2024-02-12 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributors', '0002_auto_20240212_0904'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('display', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='contributor',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='contributors', to='contributors.Tag'),
        ),
    ]
