# Generated by Django 2.2.28 on 2024-03-19 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributors', '0004_auto_20240217_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributor',
            name='fast_delivery_price',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='normal_delivery_price',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=10),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='same_day_delivery_price',
            field=models.DecimalField(decimal_places=2, default=150, max_digits=10),
        ),
    ]
