# Generated by Django 2.2.28 on 2024-06-04 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contributors', '0007_tag_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['-created_at']},
        ),
    ]
