# Generated by Django 2.2.28 on 2024-02-12 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djstripe', '0008_2_5'),
        ('consumers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumer',
            name='stripe_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='djstripe.Customer'),
        ),
    ]
