# Generated by Django 2.2.28 on 2024-03-21 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancel_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='flagged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='flagged_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Delivered', 'Delivered'), ('Redo Requested', 'Redo Requested'), ('Redone', 'Redone'), ('Refund Requested', 'Refund Requested'), ('Refunded', 'Refunded'), ('Cancel Requested', 'Cancel Requested'), ('Cancelled', 'Cancelled'), ('Flagged', 'Flagged')], default='Pending', max_length=255),
        ),
    ]
