# Generated by Django 2.2.28 on 2024-03-27 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20240321_0741'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancel_denied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='cancel_denied_reason',
            field=models.TextField(blank=True),
        ),
    ]
