# Generated by Django 2.2.28 on 2024-06-17 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20240327_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='video_processing',
            field=models.BooleanField(default=False),
        ),
    ]
